config/routes.rb
Rails.application.routes.draw do
  	resources :topics do
  	 member do
 	   post 'upvote'
 	 end
 	 member do
 	   post 'returnto'
 	 end
	end
	root 'topics#index'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic Successfully Added!' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: params[:id]+'+Topic Updated!' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic Deletion Successful!' }
      format.json { head :no_content }
    end
  end

  # Vote method
  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path, notice: params[:id])
  end

  def returnto
    @topic = Topic.find(params[:id])
    redirect_to(topics_path, notice: params[:id])
  end  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suggestion Box</title>
    <%= favicon_link_tag 'rails.png' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'Suggestion Box', topics_path, class: "navbar-brand navbar-left" %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    	<button><%= link_to 'New Topic', new_topic_path %></button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header id="myCarousel" class="carousel slide">
        <%= yield %>
    </header>
    <div class="portfolio-modal modal fade" id="messageModal" tabindex="-1" role="dialog" aria-hidden="true">
	    <div class="modal-dialog">
	        <div class="modal-content">
	            <center>
	                <div class="modal-header">
	                    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
	                    <h2></h2>
	                 </div>    
	                <br>
	                <button type="button" class="btn btn-primary btn-right" data-dismiss="modal"><i class="fa fa-times"></i> Got It</button>
	                <br><br>
	            </center>
	        </div>
	    </div>
	</div>
    <script type="text/javascript">
    	$(document).ready(function(){
    		if($("#notice").html() != undefined){
    			if($("#notice").html().split('+')[0] == ""){
		    		$("#"+$("#firstID").html()).addClass('active');	
		    	}else if($("#notice").html().split('+')[0].length > 5 || $("#notice").html() == 'Topic Deletion Successful!'){
		    		$("#"+$("#lastID").html()).addClass('active');
		    	}else{
		    		$("#"+$("#notice").html().split('+')[0]).addClass('active');
	    		}
	    		var confirmation = '';
	    		if($("#notice").html().split('+')[1] != undefined){
	    			confirmation = $("#notice").html().split('+')[1];
	    		}else if ($("#notice").html().split('+')[0].length > 5){
	    			confirmation = $("#notice").html().split('+')[0];
	    		}else if ($("#notice").html() == 'Topic Deletion Successful!'){
	    			confirmation = 'Topic Deletion Successful!';
	    		}
	    		if(confirmation != ''){
	    			$("#messageModal .modal-header h2").html(confirmation);
	    			$("#messageModal").modal('show');
	    		}
    		}
	    	$(".edit_topic input[type=submit], .new_topic input[type=submit]").addClass('btn btn-primary');
	    	$("#addVote input[type=submit]").addClass('btn btn-secondary btn-success');
	    	$(".button_to input[value='Delete']").addClass('btn btn-secondary btn-danger');
	    	$("#bs-example-navbar-collapse-1 button").addClass('btn btn-primary').css('margin-top', '1.2vh');
	    	$("#new_topic #topic_title, #new_topic #topic_description, #edit_topic_2 #topic_title, #edit_topic_2 #topic_description").attr('required', true);
	    	$("#new_topic #topic_title, #edit_topic_2 #topic_title").attr('placeholder', 'Topic Title here...');
	    	$("#new_topic #topic_description, #edit_topic_2 #topic_description").attr('placeholder', 'Topic Description...');
    	});
    </script>
  </body>
</html>

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="sb-modal modal fade" id="editTopic" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <center>
                <h1>Edit Topic</h1>
				<%= render 'form', topic: @topic %>
				<br><br>
				<%= link_to 'Show', @topic %> |
				<%= link_to 'Close', @topic %>
				<br><br>
            </center>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
		$("#editTopic").modal('show');
		$("#editTopic button a").css('color', 'white');
		$("#editTopic input[type=text], #editTopic textarea").addClass('form-control');
		$(".form-control").css('width', '20em');
	});
</script>

app/views/topics/index.html.erb
<p id="firstID" hidden><%= @topics.first.id %></p>
<p id="lastID" hidden><%= @topics.last.id %></p>
<p id="notice" hidden><%= notice %></p>

<h1 id='topics'>TOPICS</h1>
<hr>
<br><br><br>  
<div class="carousel-inner">
    <% @topics.each_with_index do |topic, index| %>
      <div class="item" id="<%= topic.id %>">
        <div class="fill">
          <div id="topicContent" style="text-align: center">
            <h2 id='topicTitle'><%= link_to topic.title, topic, title: 'View Details' %></h2>
            <h2 id='vote'><%= pluralize(topic.votes.count, "vote") %></h2>
            <h2 id='addVote'><%= button_to '+1', upvote_topic_path(topic), method: :post, title: 'Add Vote' %></h2>
            <br><br><br>
            <h2><%= button_to 'Delete', topic, method: :delete, data: { confirm: 'Delete this topic?' }, title: 'Delete Topic' %></h2>
          </div>
        </div>
      </div>
    <% end %>
</div>

<div id="controls">
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>

app/views/topics/new.html.erb
<div class="sb-modal modal fade" id="addTopic" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <center>
                <h1>New Topic</h1>

				<%= render 'form', topic: @topic %>
				<br><br>
				<%= link_to 'Close', topics_path %>
				<br><br>
            </center>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
		$("#addTopic").modal('show');
		$("#addTopic button a").css('color', 'white');
		$("#addTopic input[type=text], #addTopic textarea").addClass('form-control');
		$(".form-control").css('width', '20em');
	});
</script>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div id="topicContent2" style="text-align: center; background-color: #eee; margin-top: 8em">
	<br>
	<div>
		<h1>Topic Details</h1><br>
		<p>
		  <span>Title:</span>
		  <h4><%= @topic.title %></h4>
		</p>
		<br>
		<p>
		  <span>Description:</span>
		  <h4><%= @topic.description %></h4>
		</p>
		<br><br>
		<%= link_to 'Edit', edit_topic_path(@topic) %> |
		<%= link_to 'Back', returnto_topic_path(@topic), method: :post %>
		<br><br><br>
	</div>
</div>